### ISSUE TITLE
Trying to mkdir on a file

### ISSUE THREAD

**Issue by bitwombat** [olegkrivtsov/openbook#3]
in src/OpenBook/BookGenerator.php, you try to:

````
mkdir(dirname($dstFile), 775, true);
````
But, $dstFile is a file, not a dir, resulting in:

````
PHP Warning:  mkdir(): Permission denied in /home/gbell2/zf3_book/openbook/src/OpenBook/BookGenerator.php on line 516
````

**Comment by olegkrivtsov** [comment]
Try to use `0775` instead of `775`. If doesn't help, than you just don't have permissions for creating the directory. Try `sudo php openbook.php /path/to/your/book/directory`

**Comment by bitwombat** [comment]
It's not a permissions problem.  This is my dir.

It's that it's trying to mkdir a file, like ../en/images/netbeans/properties_browse_folders.png

**Comment by olegkrivtsov** [comment]
It can't mkdir a file, because of `dirname($dstFile)`. `dirname()` function returns directory name in which your file is located.

**Comment by bitwombat** [comment]
Oops, my mistake, forget the dir/file stuff.

Yep, permissions argument has to be 0775 or else weird things happen.
Also, `php openbook.php` must be run from the openbook dir else lots of these pop out:

````
PHP Warning:  include(): Failed opening 'data/theme/default/layout/main.php' for inclusion (include_path='.:/usr/share/php') in /home/gbell2/zf3_book/openbook/src/OpenBook/PhpRenderer.php on line 34
````

All good now.

**Comment by olegkrivtsov** [comment]
Fixed. Thanks!
